version: '3.3'
services:
  database:
    build: ./database
    restart: always
  server:
    build: ./server
    restart: always
    depends_on:
      - database
  client:
    build: ./client
    ports:
      - 3000:3000
    stdin_open: true
    depends_on:
      - server